"""
Data loading and validation utilities.

In production, data is read from Delta Lake tables via Databricks Connect.
Locally, we read from CSV files extracted by the SQL queries in sql/ or
generated by data/synthetic/generate_data.py.
"""
import pandas as pd
import yaml
from pathlib import Path
from typing import Optional


def load_config(config_path: Optional[str] = None) -> dict:
    """Load pipeline configuration."""
    if config_path is None:
        config_path = Path(__file__).parent.parent.parent / "config" / "config.yaml"
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_panel_data(path: Optional[str] = None) -> pd.DataFrame:
    """Load the store-week panel dataset.

    Production: spark.read.table("catalog.retail.fact_weekly_sales") joined
    with dim_promo_assignments.
    Local: CSV from data/raw/panel_data.csv
    """
    if path is None:
        path = Path(__file__).parent.parent.parent / "data" / "raw" / "panel_data.csv"
    df = pd.read_csv(path)
    _validate_panel(df)
    return df


def load_store_data(path: Optional[str] = None) -> pd.DataFrame:
    """Load store-level features.

    Production: spark.read.table("catalog.retail.dim_stores") joined
    with demographics, competition, traffic, supply chain tables.
    Local: CSV from data/raw/stores.csv
    """
    if path is None:
        path = Path(__file__).parent.parent.parent / "data" / "raw" / "stores.csv"
    return pd.read_csv(path)


def _validate_panel(df: pd.DataFrame) -> None:
    """Data quality checks matching what we enforce in the Databricks pipeline."""
    required_cols = ["store_id", "week", "revenue", "treated"]
    missing = set(required_cols) - set(df.columns)
    if missing:
        raise ValueError(f"Panel data missing required columns: {missing}")
    if df["revenue"].isna().any():
        raise ValueError("Panel data contains null revenue values")
    if not set(df["treated"].unique()).issubset({0, 1}):
        raise ValueError("Treatment column must be binary (0/1)")
    if df["revenue"].min() <= 0:
        raise ValueError("Revenue must be positive")
